micronaut:
  server:
    port: ${PORT:8082}


datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:soccer_fees}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    maximumPoolSize: ${DB_POOL:8}
