version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: soccer_fees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - quarkus-db-data:/var/lib/postgresql/data
      - ../common/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  backend:
    build:
      context: ..
      dockerfile: ./quarkus-app/Dockerfile
    environment:
      PORT: 8083
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: soccer_fees
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8083:8083"
    depends_on:
      - db
  frontend:
    image: nginx:alpine
    ports:
      - "3003:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  quarkus-db-data:
